package me.itlearner.jpacodegen.sample.entity.repo;

import me.itlearner.jpacodegen.sample.entity.SampleUser;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QueryDslPredicateExecutor;
import java.lang.Integer;

/**
 * repository for SampleUser generated by jpa-codegen
 * TODO
 *
 * @author generated by jpa codegen
 * Created On 2019/09/10.
 */
public interface SampleUserRepository extends JpaRepository<SampleUser, Integer>, QueryDslPredicateExecutor<SampleUser> {
}