package me.itlearner.jpacodegen.sample.form;

import lombok.Data;

/**
 * form for SampleUser generated by jpa-codegen
 * TODO
 *
 * @author generated by jpa codegen
 * Created On 2019/09/10.
 */
@Data
public class SampleUserForm {

    /**
     * TODO 字段描述
     */
    private String username;

    /**
     * TODO 字段描述
     */
    private String password;

}